export const FETCHING_SMURF = "FETCHING_SMURF";
export const FETCHING_SMURF_SUCCESS = "FETCHING_SMURF_SUCCESS";
export const POSTING_SMURF = "POSTING_SMURF";
export const POSTING_SMURF_SUCCESS = "POSTING_SMURF_SUCCESS";
