export const FETCHING_SMURF = "FETCHING_SMURF";
export const FETCHING_SMURF_SUCCESS = "FETCHING_SMURF_SUCCESS";
export const POSTING_SMURF = "POSTING_SMURF";
export const POSTING_SMURF_SUCCESS = "POSTING_SMURF_SUCCESS";
export const DELETING_SMURF = "DELETING_SMURF";
export const DELETING_SMURF_SUCCESS = "DELETING_SMURF_SUCCESS";
export const EDITING = "EDITING";
export const EDITING_SUCCESS = "EDITING_SUCCESS";
